spring:
  application:
    name: recipe-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}  # Maximum number of connections in the pool
      minimum-idle: 2            # Minimum idle connections
      idle-timeout: 30000        # Time in ms before an idle connection is removed
      connection-timeout: 30000  # Max time in ms to wait for a connection
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret: ${JWT_SECRET:hMxZ+rCq6RZwV52TmKTDLn0JwL6CV7KD0y40MAcZujh21t1BUoz7mbIhrqwwh1cboA/JS1OoRQAV317Qv6I3XQ==}
      expiration: ${JWT_EXPIRATION:86400000}


  mvc:
    cors:
      allowed-origins:
        - ${CORS_ALLOWED_ORIGIN}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  together-ai:
    api-key: ${TOGETHER_AI_API_KEY}
    base-url: "https://api.together.xyz/v1"
    embed-endpoint: "/embeddings"
    chat-endpoint: "/chat/completions"
    embed-model: ${EMBED_MODEL:BAAI/bge-base-en-v1.5-vllm}
    chat-model: ${CHAT_MODEL:mistralai/Mixtral-8x7B-Instruct-v0.1}
    chat-small-model: ${CHAT_MODEL:mistralai/Mistral-7B-Instruct-v0.2}
    client:
      max-connections: ${TOGETHER_AI_MAX_CONNECTIONS:15}
      max-idle-time-seconds: 60
      pending-acquire-timeout-seconds: 10
      pending-acquire-max-count: 50
      evict-background-seconds: 30
      enable-metrics: true
      response-timeout-seconds: 60
      connect-timeout-millis: 10000
      read-timeout-seconds: 60
      write-timeout-seconds: 60

# Rate limiter configuration
rate-limiter:
  max-per-minute: 30
  max-per-hour: 100
  one-minute-in-seconds: 60
  one-hour-in-seconds: 3600

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com/v1
  chat-endpoint: /v1/chat/completions
  chat-model: gpt-5-nano

#remove later
logging:
  level:
    org.hibernate.SQL: INFO
    com.zaxxer.hikari: INFO
  config: classpath:logback-spring.xml
  loki:
    url: ${GRAFANA_LOKI_URL}
    username: ${GRAFANA_LOKI_USER}
    password: ${GRAFANA_LOKI_TOKEN}
server:
  port: ${PORT:8081}
app:
  env: default