spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: table-dog-brown-fibber
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect




#remove later
logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.sql.ast: WARN
    org.hibernate.orm.results.graph: WARN
    org.hibernate.internal.AbstractSharedSessionContract: ERROR