spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5      # Max number of connections in the pool
      minimum-idle: 2            # Minimum idle connections
      idle-timeout: 30000        # Time in ms before an idle connection is removed
      connection-timeout: 30000  # Max time in ms to wait for a connection
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    cors:
      allowed-origins:
        - ${CORS_ALLOWED_ORIGIN}


#remove later
logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.sql.ast: WARN
    org.hibernate.orm.results.graph: WARN
    org.hibernate.internal.AbstractSharedSessionContract: ERROR